app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_homepage:
    path:     /
    defaults: { _controller: AppBundle:DefaultController:indexAction }

_codecache:
    path:     /code-cache/
    defaults: { _controller: AppBundle:CodeCacheController:indexAction }