app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_homepage:
    path:     /notebook/
    defaults: { _controller: AppBundle:DefaultController:indexAction }

_editor-controller:
    path:     /notebook/editor/
    defaults: { _controller: AppBundle:EditorController }

logout:
    path:   /logout/

default_security_target:
    path:     /notebook/