app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_frontend-homepage:
    path:     /
    defaults: { _controller: AppBundle:FrontendController:indexAction }

_homepage:
    path:     /notebook/
    defaults: { _controller: AppBundle:DefaultController:indexAction }

_codecache:
    path:     /notebook/code-cache/
    defaults: { _controller: AppBundle:CodeCacheController:indexAction }