# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.services.helper:
        class: AppBundle\Services\Helper
    app.services.foldersProjects:
        class: AppBundle\Services\FoldersProjects
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
    app.services.getFoldersProjects:
        class: AppBundle\Services\GetFoldersProjects
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]