AppBundle\Entity\Project:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
            type: integer
            column: user_id
        name:
            type: string
            length: 255
        isCompleted:
            type: boolean
            column: is_completed
        dateModified:
            type: datetime
            column: date_modified
        dateCreated:
            type: datetime
            column: date_created
        dateCompleted:
            type: datetime
            column: date_completed
            nullable: true
    lifecycleCallbacks: {  }
